### ISSUE TITLE
connect coveralls.io

### ISSUE THREAD

**Issue by hugojosefson** [hugojosefson/duplicati-generate-config#15]
## ~~Blocked~~
~~waiting for `@std/esm#0.11.3`. See https://github.com/standard-things/esm/issues/117~~

Implemented with babel instead: 5e6b416e5669abbf9b8ad75d96a09d0ff0b70f38

## TODO
- [x] https://github.com/nickmerwin/node-coveralls#readme
- [x] https://coveralls.io/github/hugojosefson/duplicati-generate-config
- [x] Add coverage shield to `README.md`
